### PR TITLE
Don't define Lift instances for containers >= 0.6.6

### LINKED ISSUE #32: Watch out for the next containers
The next version of `containers` will implement its own `Lift` instances.

### PR DESCRIPTION
**Pull request by TeofilC**
This MR fixes building with the new version of containers that has Lift instances defined

Fixes #32

### CODE REVIEW

**Comment by treeowl** [comment]
Would it be better to move all the `containers` instances to their own module so there aren't such large conditional blocks?

**Comment by TeofilC** [comment]
Good point. I'll make that change.

Another thing is that we probably don't want to depend on containers if they are recent enough, but I'm not sure how to encode that in the cabal file. Perhaps it's not a worry since containers is a boot package

**Comment by treeowl** [comment]
There's no way to encode that, no. As you say, it doesn't really matter in practice.

**Comment by TeofilC** [comment]
Now that I've begun to implement moving the containers instance into its own module, I'm not sure it makes things better. We still have to wrap the entire thing in an `if` otherwise we get a duplicate instance when compiling that module, and there's the LIFT_TYPED_DEFAULT macro that needs to be duplicated.

**Comment by treeowl** [comment]
Wrapping the whole module is easier to understand than wrapping a big chunk, IMO. A `.h` file can hold that macro if desired. Up to you, really.

**Comment by TeofilC** [comment]
I think I have a mild preference to keep it in one file, but I also get the perspective that wrapping the entire thing is easier to read. I'll wait to see what bennofs says

**Comment by ysangkok** [comment]
@bennofs Have you seen this? Because I see you hadn't previous been tagged.

**Comment by bennofs** [comment]
Looks good to me. We can separate this into different modules later if we want to.

**Comment by TeofilC** [comment]
Thanks everyone

**Pull request merged**
