### PR TITLE
More instances

### LINKED ISSUE #12: Lift instances for `NonEmpty` and `Void`.
This instances would be good to be here, for `base` / `template-haskell` versions where they don't have it.

Next `void` and `semigroups` will have these instances, providing them when they are not in `base`.

I can make a PR.

Related:
- https://github.com/ekmett/semigroups/issues/89
- https://github.com/ekmett/void/issues/16 

cc @RyanGlScott

### PR DESCRIPTION
**Pull request by phadej**
This PR primarily resolves #12.

Additionally
- I dropped the `th-lift` dependency, as it's not needed
- Made package use `TemplateHaskellQuotes` so #9 is also resolved:

```
% cabal new-build --ghcjs -w /opt/ghcjs/8.4/bin/ghcjs
Warning: don't know how to find change monitoring files for the installed
package databases for ghcjs
Resolving dependencies...
Build profile: -w ghcjs-8.4.0.1 -O1
In order, the following will be built (use -v for more details):
 - primitive-0.6.4.0 (lib) (requires build)
 - vector-0.12.0.2 (lib) (requires build)
 - th-lift-instances-0.1.11 (lib) (first run)
Starting     primitive-0.6.4.0 (lib)
Building     primitive-0.6.4.0 (lib)
Installing   primitive-0.6.4.0 (lib)
Completed    primitive-0.6.4.0 (lib)
Starting     vector-0.12.0.2 (lib)
Building     vector-0.12.0.2 (lib)
Installing   vector-0.12.0.2 (lib)
Completed    vector-0.12.0.2 (lib)
Configuring library for th-lift-instances-0.1.11..
Preprocessing library for th-lift-instances-0.1.11..
Building library for th-lift-instances-0.1.11..
[1 of 1] Compiling Instances.TH.Lift ( src/Instances/TH/Lift.hs, /home/ogre/Documents/other-haskell/th-lift-instances/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/th-lift-instances-0.1.11/build/Instances/TH/Lift.js_o )
```

---

For comparison `master` also works for me:

```
% cabal new-build --ghcjs -w /opt/ghcjs/8.4/bin/ghcjs
Warning: don't know how to find change monitoring files for the installed
package databases for ghcjs
Resolving dependencies...
Build profile: -w ghcjs-8.4.0.1 -O1
In order, the following will be built (use -v for more details):
 - th-lift-0.7.11 (lib) (requires build)
 - th-lift-instances-0.1.11 (lib) (configuration changed)
Starting     th-lift-0.7.11 (lib)
Building     th-lift-0.7.11 (lib)
Installing   th-lift-0.7.11 (lib)
Completed    th-lift-0.7.11 (lib)
Configuring library for th-lift-instances-0.1.11..
Preprocessing library for th-lift-instances-0.1.11..
Building library for th-lift-instances-0.1.11..
[1 of 1] Compiling Instances.TH.Lift ( src/Instances/TH/Lift.hs, /home/ogre/Documents/other-haskell/th-lift-instances/dist-newstyle/build/x86_64-linux/ghcjs-8.4.0.1/th-lift-instances-0.1.11/build/Instances/TH/Lift.js_o )
Linking Template Haskell ()
Linking Template Haskell (ThRunner1)
```

Note the `ThRunner1`, it something which is not the most reliable piece, I think.

### CODE REVIEW

**Comment by phadej** [comment]
FWIW, I would advice not to build and upload docs with GHC-8.0 (or at all). Hackage's doc-builder is nowadays reliable.

The downside that e.g. `Lift` link links to `template-haskell-2.10`, which is old. Also `Map` etc. containers type links to old `container` release (the one bundled with GHC-8.0).

**Comment by phadej** [comment]
travis is finally satisfied

**Comment by bennofs** [comment]
Thank you a lot for fixing travis. I'll take a detailed look at this tomorrow and merge + release.

**Comment by phadej** [comment]
ping @bennofs

**Comment by phadej** [comment]
Thanks Benno.

After release I discovered a small mess I created: https://github.com/mboes/th-lift/pull/39
I'll make a follow up pull request once/if we get `th-lift` release. Sorry for inconvenience, but let's try to find good home for the orphans.

**Pull request merged**
